### ISSUE TITLE
DataLoad section: hard-coded DataFiles and QVD name

### ISSUE THREAD

**Issue by alexometis** [Qlik-PE/qlik-azure-cost-explorer#2]
I think this:
```
FROM [lib://DataFiles/azure_consumption_2*.qvd](qvd)
Where Rand()>0.45;
```
Should be this:
```
FROM [lib://$(DC_QVD)/git_azure_consumption_*.qvd](qvd);
```

**Comment by cleveranjos** [comment]
Thanks for pointing

**Comment by somasekaran1992** [comment]
Hi, 
To create Rest API connection as mentioned in the document what authentication type and credentials one should use ? can you please help me on this.
